import express from 'express';
import { body, validationResult } from 'express-validator';
import QRCode from 'qrcode';
import {
  hashPassword,
  comparePassword,
  generateToken,
  authMiddleware
} from '../config/auth.js';
import {
  createUser,
  getUserByEmail,
  getUserById,
  createStudent,
  createTeacher,
  getTeacherByUserId,
  trackLogin,
  getResumeState,
  saveResumeState
} from '../config/database.js';
import { getRegistrationGrants } from '../config/subjectAccess.js';

const router = express.Router();

async function generateAndSaveBarcode(supabase, studentId, studentCode) {
  try {
    const qrDataURL = await QRCode.toDataURL(studentCode, {
      width: 300, margin: 2,
      color: { dark: '#1a1a2e', light: '#ffffff' },
      errorCorrectionLevel: 'M',
    });
    await supabase.from('students')
      .update({ barcode_url: qrDataURL, barcode_generated_at: new Date().toISOString() })
      .eq('id', studentId);
    return qrDataURL;
  } catch (e) {
    console.error('[StudentID] Barcode generation failed:', e.message);
    return null;
  }
}

/**
 * POST /api/auth/signup
 * Register a new user (student, parent, or teacher)
 */
router.post(
  '/signup',
  [
    body('email').isEmail(),
    body('password').isLength({ min: 6 }),
    body('full_name').notEmpty(),
    body('role').isIn(['student', 'parent', 'teacher'])
  ],
  async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() });
    }

    try {
      const { email, password, full_name, role, parent_id, school_name, form_level, subject, bio } = req.body;

      // Check if user already exists
      const existingUser = await getUserByEmail(email);
      if (existingUser) {
        return res.status(400).json({ error: 'User already exists' });
      }

      // Hash password
      const passwordHash = await hashPassword(password);

      // Create user
      const user = await createUser(email, passwordHash, full_name, role);

      // If student, create student profile
      let studentCode = null;
      let barcodeUrl = null;
      if (role === 'student') {
        const { supabase } = await import('../config/database.js');
        await supabase.from('students').insert({ id: user.id, name: full_name, email });

        // Fetch auto-generated student_code from trigger
        const { data: studentRow } = await supabase
          .from('students').select('id, student_code').eq('id', user.id).maybeSingle();
        studentCode = studentRow?.student_code ?? null;

        // If trigger hasn't run yet, generate fallback code with uniqueness check
        if (!studentCode) {
          console.warn('[Auth] student_code not generated by trigger — generating manually');
          let codeExists = true;
          while (codeExists) {
            studentCode = 'LRN-' + Math.floor(Math.random() * 100000000).toString().padStart(8, '0');
            const { count } = await supabase
              .from('students')
              .select('*', { count: 'exact', head: true })
              .eq('student_code', studentCode);
            codeExists = (count ?? 0) > 0;
          }
          await supabase.from('students').update({ student_code: studentCode }).eq('id', user.id);
        }

        // Generate QR barcode
        barcodeUrl = await generateAndSaveBarcode(supabase, user.id, studentCode);
        console.log(`[StudentID] ${studentCode} assigned to ${full_name}`);

        // Grant subject access rows on registration
        try {
          const { data: settings } = await supabase.from('platform_settings').select('key,value');
          const trialDays = parseInt((settings || []).find(s => s.key === 'trial_days')?.value || '7');
          const chosenSubjects = req.body.subjects || [];
          const grants = getRegistrationGrants(user.id, chosenSubjects, trialDays);
          if (grants.length > 0) {
            await supabase.from('subject_access').upsert(grants, { onConflict: 'student_id,subject', ignoreDuplicates: true });
          }
        } catch (grantErr) {
          console.error('[Auth] subject_access grant failed:', grantErr.message);
        }

        const parentEmail = req.body.parent_email;
        if (parentEmail) {
          const normalizedParentEmail = parentEmail.toLowerCase().trim();
          // Record in student_parent_emails so parent can claim at signup
          await supabase.from('student_parent_emails').upsert(
            [{ student_id: user.id, parent_email: normalizedParentEmail, status: 'pending' }],
            { onConflict: 'student_id,parent_email', ignoreDuplicates: true }
          );
          await supabase.from('students').update({ parent_email: normalizedParentEmail }).eq('id', user.id);
          // If parent already has an account, create connection immediately
          const parentUser = await getUserByEmail(normalizedParentEmail);
          if (parentUser && parentUser.role === 'parent') {
            await supabase.from('parent_student_connections').upsert(
              [{
                parent_id: parentUser.id,
                student_id: user.id,
                student_code: studentCode || '',
                connection_method: 'email_prelink',
                connection_type: 'parent',
                status: 'pending',
                parent_name: parentUser.full_name,
                parent_email: normalizedParentEmail,
                initiated_by: 'student',
              }],
              { onConflict: 'parent_id,student_id', ignoreDuplicates: true }
            );
            await supabase.from('student_parent_emails')
              .update({ status: 'claimed', claimed_at: new Date().toISOString() })
              .eq('student_id', user.id).eq('parent_email', normalizedParentEmail);
          }
        }
      }

      // If teacher, create teacher profile
      if (role === 'teacher') {
        await createTeacher(user.id, subject || 'Mathematics', 4, bio || null);
      }

      // Generate token
      const token = generateToken(user.id, role);

      res.status(201).json({
        message: 'User registered successfully',
        token,
        user: {
          id: user.id,
          email: user.email,
          full_name: user.full_name,
          role: user.role,
          student_code: studentCode,
          barcode_url: barcodeUrl,
        }
      });
    } catch (error) {
      console.error('Signup error:', error);
      res.status(500).json({ error: error.message });
    }
  }
);

/**
 * POST /api/auth/login
 * Login user and return JWT token
 */
router.post(
  '/login',
  [
    body('email').isEmail(),
    body('password').notEmpty()
  ],
  async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() });
    }

    try {
      const { email, password } = req.body;

      // Find user
      const user = await getUserByEmail(email);
      if (!user) {
        return res.status(401).json({ error: 'Incorrect email or password. Please try again.' });
      }

      // Compare password
      const isPasswordValid = await comparePassword(password, user.password_hash);
      if (!isPasswordValid) {
        return res.status(401).json({ error: 'Incorrect email or password. Please try again.' });
      }

      // Generate token
      const token = generateToken(user.id, user.role);

      const loginMeta = await trackLogin(
        user.id,
        user.role,
        user.email,
        req.headers['user-agent'] || null
      );

      const resumeState = await getResumeState(user.id, user.role);

      // Create a default resume state for first login users
      if (loginMeta.isFirstLogin && !resumeState) {
        await saveResumeState(user.id, user.role, {
          last_screen: user.role === 'teacher'
            ? 'teacher_onboarding'
            : user.role === 'parent'
              ? 'parent_dashboard'
              : 'student_dashboard',
          subject: null,
          topic: null,
          subtopic: null,
          lesson_id: null,
          quiz_id: null,
          progress_percent: 0
        });
      }

      const latestResumeState = await getResumeState(user.id, user.role);

      // Fetch form_level for students
      let formLevel = null;
      let subjects = null;
      let onboardingComplete = false;
      if (user.role === 'student') {
        try {
          const { supabase } = await import('../config/database.js');
          // Try user_id column first, fall back to id column
          let { data: studentRow } = await supabase
            .from('students')
            .select('form_level, subjects')
            .eq('id', user.id)
            .maybeSingle();
          if (!studentRow) {
            const { data: byId } = await supabase
              .from('students')
              .select('form_level, subjects')
              .eq('id', user.id)
              .maybeSingle();
            studentRow = byId;
          }
          formLevel = studentRow?.form_level ?? null;
          subjects = studentRow?.subjects ?? null;
          onboardingComplete = studentRow?.onboarding_complete ?? false;
        } catch (_) { /* non-fatal */ }
      }

      res.json({
        message: loginMeta.isFirstLogin ? 'Welcome to Learnova!' : 'Welcome back!',
        token,
        is_first_login: loginMeta.isFirstLogin,
        login_count: loginMeta.loginCount,
        resume_state: latestResumeState,
        form_level: formLevel,
        onboarding_complete: onboardingComplete,
          subjects: subjects,
        user: {
          id: user.id,
          email: user.email,
          full_name: user.full_name,
          role: user.role
        }
      });
    } catch (error) {
      console.error('Login error:', error);
      res.status(500).json({ error: error.message });
    }
  }
);

/**
 * GET /api/auth/me
 * Get current user info (requires auth token)
 */
router.get('/me', authMiddleware, async (req, res) => {
  try {
    const user = await getUserById(req.user.userId);
    res.json({
      user: {
        id: user.id,
        email: user.email,
        full_name: user.full_name,
        role: user.role
      }
    });
  } catch (error) {
    console.error('Get user error:', error);
    res.status(500).json({ error: error.message });
  }
});

/**
 * GET /api/auth/student-profile
 * Get student profile (requires auth + student role)
 */
router.get('/student-profile', authMiddleware, async (req, res) => {
  try {
    if (req.user.role !== 'student') {
      return res.status(403).json({ error: 'Students only' });
    }

    const { supabase } = await import('../config/database.js');
    const { data: student, error } = await supabase
      .from('students')
      .select('*')
      .eq('id', req.user.userId)
      .maybeSingle();

    if (error) throw error;
    if (!student) {
      return res.status(404).json({ error: 'Student profile not found' });
    }

    res.json({ student });
  } catch (error) {
    console.error('Get student profile error:', error);
    res.status(500).json({ error: error.message });
  }
});

/**
 * GET /api/auth/teacher-profile
 * Get teacher profile (requires auth + teacher role)
 */
router.get('/teacher-profile', authMiddleware, async (req, res) => {
  try {
    if (req.user.role !== 'teacher') {
      return res.status(403).json({ error: 'Teachers only' });
    }

    const teacher = await getTeacherByUserId(req.user.userId);
    if (!teacher) {
      return res.status(404).json({ error: 'Teacher profile not found' });
    }

    res.json({ teacher });
  } catch (error) {
    console.error('Get teacher profile error:', error);
    res.status(500).json({ error: error.message });
  }
});

/**
 * PATCH /api/auth/update-form
 * Save the student's form level (persists across devices/browsers)
 */
router.patch('/update-form', authMiddleware, async (req, res) => {
  try {
    const { form_level } = req.body;
    if (!form_level) return res.status(400).json({ error: 'form_level required' });

    const { supabase } = await import('../config/database.js');

    // Students are created at signup with `id = userId` (user_id column is null).
    // We run both updates unconditionally � whichever matches will save the form.
    await supabase.from('students').update({ form_level }).eq('id', req.user.userId);
    await supabase.from('students').update({ form_level }).eq('id', req.user.userId);

    res.json({ ok: true, form_level });
  } catch (error) {
    console.error('update-form error:', error);
    res.status(500).json({ error: error.message });
  }
});


// POST /api/student/profile/onboard
// Saves form level, subjects, language and marks onboarding complete
router.post('/student/profile/onboard', async (req, res) => {
  try {
    const { student_id, form_level, subjects, preferred_language, onboarding_complete } = req.body;
    if (!student_id) return res.status(400).json({ error: 'student_id required' });
    const { supabase } = await import('../config/database.js');
    const { error } = await supabase.from('students')
      .update({
        form_level: form_level ? String(form_level) : null,
        subjects: subjects || [],
        preferred_language: preferred_language || 'en',
        onboarding_complete: onboarding_complete || true,
      })
      .eq('id', student_id);
    if (error) throw error;
    res.json({ ok: true });
  } catch (e) {
    console.error('Onboard error:', e);
    res.status(500).json({ error: e.message });
  }
});

export default router;










