import express from 'express';
import { supabase } from '../config/database.js';

const router = express.Router();

// ── GET /api/topic-animations ──────────────────────────────────────────────
// Query params: subject, topic, form (optional)
// Returns the pre-built animation for a topic from Supabase.
// All animations generated by Claude (proprietary IP) — never DeepSeek.
router.get('/', async (req, res) => {
  try {
    const { subject, topic, form } = req.query;
    if (!subject || !topic) {
      return res.status(400).json({ error: 'subject and topic are required' });
    }

    let query = supabase
      .from('topic_animations')
      .select('id, title_bm, animation_type, steps, graph_config, color_scheme, subtopic')
      .ilike('subject', subject.trim())
      .ilike('topic', `%${topic.trim()}%`)
      .order('spm_weightage', { ascending: false })
      .limit(1);

    if (form) {
      query = query.ilike('form', `%${form}%`);
    }

    const { data, error } = await query.maybeSingle();

    if (error) {
      console.error('[TopicAnimation] DB error:', error.message);
      return res.status(500).json({ error: 'Database error' });
    }

    if (!data) {
      return res.status(404).json({ error: 'No animation found for this topic' });
    }

    console.log(`[TopicAnimation] Served: ${data.title_bm} (${data.animation_type}, ${data.steps?.length} steps)`);

    return res.json({
      id: data.id,
      title: data.title_bm,
      type: data.animation_type,
      steps: data.steps || [],
      graph_config: data.graph_config || null,
      color_scheme: data.color_scheme || 'purple',
      subtopic: data.subtopic || '',
    });

  } catch (e) {
    console.error('[TopicAnimation] Error:', e);
    res.status(500).json({ error: 'Server error' });
  }
});

// ── GET /api/topic-animations/list ────────────────────────────────────────
// Lists all available animations for a subject (for pre-loading)
router.get('/list', async (req, res) => {
  try {
    const { subject } = req.query;

    let query = supabase
      .from('topic_animations')
      .select('subject, form, topic, subtopic, animation_type, title_bm, color_scheme')
      .order('subject')
      .order('form');

    if (subject) query = query.ilike('subject', subject.trim());

    const { data, error } = await query;
    if (error) return res.status(500).json({ error: error.message });

    res.json(data || []);
  } catch (e) {
    res.status(500).json({ error: 'Server error' });
  }
});

export default router;
